# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

logger:
  default: debug
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

influxdb:
  host: localhost
  port: 8086
  database: HomeAssistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: http://192.168.8.10:9541

binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
#switch: !include switches.yaml
mqtt: !include mqtt.yaml