
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

influxdb:
  host: localhost
  port: 8086
  database: HomeAssistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state
